const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const orderStatus = fs.readFileSync(path.join(__dirname, '..', 'api', 'estado-pedido.js'), 'utf8');
const shippingApi = fs.readFileSync(path.join(__dirname, '..', 'api', 'envios.js'), 'utf8');

test('public order-status lookup does not create review invitations as a read side effect', () => {
  assert.doesNotMatch(orderStatus, /ensureReviewInvites/);
  assert.match(orderStatus, /SELECT r\.product_id,r\.review_token,r\.status/);
});

test('review invitations remain generated by delivery synchronization and automation', () => {
  assert.match(shippingApi, /await ensureReviewInvites\(sql, orders\[0\]\.id\)/);
  assert.match(shippingApi, /await ensureReviewInvites\(sql, order\.id\)/);
  assert.match(shippingApi, /queueAndSendOrderNotification\(sql, orders\[0\]\.id, 'review_invite'\)/);
});
